name: fft_nullsafety
description: A library for fourier transformations using the Cooley-Tukey algorithm
version: 0.2.1
author: HAKStudio <hakstudioo@gmail.com>
homepage: https://github.com/hakstudio/dart_lang_fft

environment:
  sdk: ">=2.12.0 <4.0.0"

dependencies:
  my_complex_nullsafety: ^0.1.2
  tuple: ^2.0.2

dev_dependencies:
  test: '>=0.12.0 <2.0.0'